apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: demo-microservice
spec:
  components:
    - name: demo-microservice
      type: deployment
      properties:
        image: "ghcr.io/gepaplexx/demo-microservice"
        tag: "413b395"
        ports:
          - port: 8080
            expose: true
        env:
          - name: AB_JOLOKIA_OFF
            value: 'true'
          - name: AB_PROMETHEUS_OFF
            value: 'true'
          - name: JAVA_MAX_MEM_RATIO
            value: '95'
          - name: JAVA_OPTIONS
            value: '-Djava.net.preferIPv4Stack=true'
        resources:
          requests:
            cpu: "75m"
      traits:
        - type: liveness
          properties:
            path: "/q/health/live"
        - type: readiness
          properties:
            path: "/q/health/ready"
        - type: service-monitor
          properties:
            path: "/q/metrics"
        - type: alerting
          properties:
            rules:
              - name: "not-running"
                summary: "No instance of the application is running"
                expr: 'sum(up{job="demo-microservice"}) < 1 or absent(up{job="demo-microservice"})'
                interval: "10s"
                for: "10s"
                severity: "critical"
        # Example for Loki alerts, not tested yet
#        - type: loki-alerting
#          properties:
#            groups:
#              - interval: "10s"
#                limit: 0
#                name: "rule-1"
#                rules:
#                  - alert: "alert-1"
#                    expr: "sum(count_over_time({level=\"error\",kubernetes_namespace_name=\"scch-grafana-playground\"} | json | kubernetes_container_name=\"demo-microservice\" [30s]))"
#                    for: "10s"
        - type: dashboard
