apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: gepardenblick
spec:
  components:
    - name: gepardenblick
      type: deployment
      properties:
        image: "ghcr.io/gepaplexx/gepardenblick"
        tag: "5d8667d"
        ports:
          - port: 8080
            expose: true
          - port: 8443
          - port: 8778
        env:
          - name: AB_JOLOKIA_OFF
            value: 'true'
          - name: AB_PROMETHEUS_OFF
            value: 'true'
          - name: JAVA_MAX_MEM_RATIO
            value: '95'
          - name: JAVA_OPTIONS
            value: '-Djava.net.preferIPv4Stack=true'
      traits:
        - type: liveness
          properties:
            path: "/q/health/live"
        - type: readiness
          properties:
            path: "/q/health/ready"
        - type: secret
          properties:
            name: gepardenblick-config
            mountPath: "/work/config"
            data:
              application.properties: <SET_ME> # TODO
            resources:
              requests:
                cpu: "75m"
