apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: gepardenblick
spec:
  components:
    - name: gepardenblick
      type: deployment
      properties:
        image: "ghcr.io/gepaplexx/gepardenblick"
        tag: "5d8667d"
        ports:
          - port: 8080
            expose: true
          - port: 8443
          - port: 8778
        env:
          - name: AB_JOLOKIA_OFF
            value: 'true'
          - name: AB_PROMETHEUS_OFF
            value: 'true'
          - name: JAVA_MAX_MEM_RATIO
            value: '95'
          - name: JAVA_OPTIONS
            value: '-Djava.net.preferIPv4Stack=true'
        resources:
          requests:
            cpu: "75m"
      traits:
        - type: liveness
          properties:
            path: "/q/health/live"
        - type: readiness
          properties:
            path: "/q/health/ready"
        - type: secret
          properties:
            name: gepardenblick-config
            mountPath: "/work/config"
            data:
              application.properties: <SET_ME> # TODO
        - type: service-monitor
          properties:
            path: "/q/metrics"
        - type: alerting
          properties:
            rules:
              - name: "not-running"
                summary: "No instance of the application is running"
                expr: 'sum(up{job="gepardenblick"}) < 1 or absent(up{job="gepardenblick"})'
                interval: "10s"
                for: "10s"
                severity: "critical"
