apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: db-postgresql
  annotations:
    definition.oam.dev/description: "Deploy a postgresql database"
spec:
  workload:
    definition:
      apiVersion: apps/v1
      kind: StatefulSet
  schematic:
    kube:
      template:
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        spec:
          destination:
            namespace: context.namespace
            server: 'https://kubernetes.default.svc'
          project: default # FIXME for simplicity
          source:
            chart: 'postgresql'
            repoURL: 'https://charts.bitnami.com/bitnami'
            targetRevision: '11.0.3' # TODO make it configerable
            helm:
              parameters:
              - name: primary.containerSecurityContext.enabled
                value: "false"
              - name: primary.podSecurityContext.enabled
                value: "false"
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - CreateNamespace=true
      parameters:
      - name: name
        required: true
        type: string
        fieldPaths:
        - metadata.name
