apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: mega-frontend-main
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mega-frontend
    app.kubernetes.io/version: 0.0.1
    helm.sh/chart: mega-frontend-0.1.18
  name: mega-frontend-main
  namespace: mega-frontend-main
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: mega-frontend-main
      app.kubernetes.io/name: mega-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: mega-frontend-main
        app.kubernetes.io/name: mega-frontend
    spec:
      containers:
      - image: ghcr.io/gepaplexx/mega-frontend:91de49e
        imagePullPolicy: IfNotPresent
        name: mega-frontend-main
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/cache/nginx
          name: cache
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: cache