apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: weckdengeparden
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: weckdengeparden
    app.kubernetes.io/version: 0.0.1
    helm.sh/chart: weckdengeparden-0.1.3
  name: weckdengeparden
  namespace: weckdengeparden
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: weckdengeparden
      app.kubernetes.io/name: weckdengeparden
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: weckdengeparden
        app.kubernetes.io/name: weckdengeparden
    spec:
      containers:
      - env:
        - name: AB_JOLOKIA_OFF
          value: "true"
        - name: AB_PROMETHEUS_OFF
          value: "true"
        - name: JAVA_MAX_MEM_RATIO
          value: "95"
        - name: JAVA_OPTIONS
          value: -Djava.net.preferIPv4Stack=true
        image: ghcr.io/gepaplexx/weckdengeparden:77facc6
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/live
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: weckdengeparden
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/ready
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /work/config/
          name: secret-weckdengeparden
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: secret-weckdengeparden
        secret:
          defaultMode: 420
          secretName: secret-weckdengeparden